stages:
  - build
  - up
  - test
  - chaos_test
  - verify
  - observe
  - recovery
  - report
  - cleanup

image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

# 1. Build Stage
build:
  stage: build
  script:
    - docker compose build

# 2. Up Stage
up:
  stage: up
  script:
    - docker compose up -d
    - echo "Waiting for all services to be heathly..."
    - sleep 60
    - docker compose ps

# 3. Test Stage
test_normal:
  stage: test
  script:
    - docker compose up -d
    - sleep 5
    - docker run --rm --network app_default curlimages/curl docker run --rm --network app_default curlimages/curl curl -f http://app:5000

# 4. Chaos Test Stage
chaos_test:
  stage: chaos_test
  script:
    - echo "Testing under chaos (toxiproxy)"
    - |
      TIME=$(docker run --rm --network app_default curlimages/curl curl -o /dev/null -s -w "%{time_total}" http://toxiproxy:8666 || echo "fail")
      echo "Response time: $TIME"
      if [ "$TIME" = "fail" ]; then echo "Service unreachable ❌"; exit 1; fi

# 5. Verify Stage
verify:
  stage: verify
  script:
    - echo "Verifying system stability"
    - |
      LATENCY=$(docker run --rm --network app_default curlimages/curl curl -o /dev/null -s -w "%{time_total}" http://toxiproxy:8666)
      echo "Latency: $LATENCY"
      # Using awk for floating point comparison
      awk -v n="$LATENCY" 'BEGIN {if (n > 6) exit 1}' || (echo "Too slow ❌" && exit 1)
    - docker run --rm --network app_default curlimages/curl curl -f http://toxiproxy:8666 || exit 1

# 6. Observe Stage
observe:
  stage: observe
  script:
    - sleep 15
    - echo "Checking metrics from Prometheus"
    - docker run --rm --network app_default curlimages/curl curl -f "http://prometheus:9090/api/v1/query?query=up" || echo "Prometheus not responding"
    - echo "Checking logs from Loki"
    - docker run --rm --network app_default curlimages/curl curl -s "http://loki:3100/loki/api/v1/labels" || true

# 7. Recovery Stage
recovery:
  stage: recovery
  script:
    - echo "Waiting for system recovery..."
    - sleep 20
    - docker run --rm --network app_default curlimages/curl docker run --rm --network app_default curlimages/curl docker run --rm --network app_default curlimages/curl curl -f http://app:5000 || exit 1

# 8. Report Stage
report:
  stage: report
  script:
    - echo "Generating report..."
    - |
      echo "Chaos Engineering Report" > report.md
      echo "-------------------------" >> report.md
      echo "✅ System survived chaos" >> report.md
      echo "✅ Monitoring active" >> report.md
      echo "✅ Recovery successful" >> report.md
    - cat report.md
  artifacts:
    paths:
      - report.md

# 9. Cleanup Stage
cleanup:
  stage: cleanup
  script:
    - docker compose down
  when: always
